Changes to be committed:
lfapac-open-source-evangelist/fabric-docs-i18n pull request #46
Opened 2023-07-31 07:30 UTC by terizhao

modified:   docs/locale/zh_CN/source/discovery-overview.rst

2023-08-01 02:50 UTC, zRich requested changes

2023-08-01 02:50 UTC, zRich commented on docs/locale/zh_CN/source/discovery-overview.rst
> +为了在对等节点上执行链码、向订购节点提交交易并获取交易状态的更新，应用程序通过一个由SDK公开的API进行连接。
orderer在fabric里面是排序的意思。

2023-08-01 02:50 UTC, zRich commented on docs/locale/zh_CN/source/discovery-overview.rst
> +然而，SDK需要大量的信息，以便让应用程序能够连接到相关的网络节点。除了通道上订购者和对等节点的CA和TLS证书,
orderer service翻译成排序服务，orderer peer/node 翻译成排序节点

2023-08-02 02:12 UTC, terizhao commented on docs/locale/zh_CN/source/discovery-overview.rst
> +为了在对等节点上执行链码、向订购节点提交交易并获取交易状态的更新，应用程序通过一个由SDK公开的API进行连接。
address it in the new commit.

2023-08-02 02:12 UTC, terizhao commented on docs/locale/zh_CN/source/discovery-overview.rst
> +然而，SDK需要大量的信息，以便让应用程序能够连接到相关的网络节点。除了通道上订购者和对等节点的CA和TLS证书,
address it in the new commit

2023-08-02 05:53 UTC, zRich approved these changes

2023-08-02 05:53 UTC, merged