finish proof reading of "peer-chaincode-devmode.md" #16
lfapac-open-source-evangelist/fabric-docs-i18n pull request #51
Opened 2023-08-24 07:33 UTC by winterpi

finish proof reading of "peer-chaincode-devmode.md" #16

2023-08-30 09:51 UTC, Chengxuan commented on docs/locale/zh_CN/source/couchdb_tutorial.rst
> +CouchDB 是一个可选的、可替换的状态数据库，支持将账本的数据转为 JSON 格式，并数据内容的富查询，而不仅仅是基于 key 的查询。
```suggestion
CouchDB 是一个可选的、可替换的状态数据库，支持将账本的数据转为 JSON 格式，并支持数据内容的富查询，而不仅仅是基于 key 的查询。
```

2023-08-30 09:57 UTC, Chengxuan commented on docs/locale/zh_CN/source/couchdb_tutorial.rst
> +如果您想将 JSON 和二进制数据混合使用，同样可以使用 CouchDB ，但只能基于键、键范围和复合键来查询二进制数据。
```suggestion
如果需要同时支持 JSON 和二进制数据，同样可以使用 CouchDB ，但二进制数据只能基于键、键范围和复合键来查询。
```

2023-08-30 10:07 UTC, Chengxuan commented on docs/locale/zh_CN/source/peer-chaincode-devmode.md
> +# 在开发模式下运行智能合约
```suggestion
# 在开发模式下运行链码
```

2023-08-30 10:08 UTC, Chengxuan commented on docs/locale/zh_CN/source/peer-chaincode-devmode.md
> +**注意:** 为了在peer上使用开发模式("DevMode")，网络中的所有节点必须禁用TLS通信。在生产网络环境下强烈推荐使用TLS通信，所以永远不要在开发模式下启动一台生产型peer。不要将本教程中使用的网络作为任何形式的生产网络的模板。参考[部署一个生产网络](deployment_guide_overview.html)来了解怎样部署一个生产型网络。还可以参考 [Fabric测试网络
@winterpi 这一段中有一些"链码“被重置成了"chaincode"，不确定符合翻译标准

2023-08-30 10:12 UTC, Chengxuan commented on docs/locale/zh_CN/source/peer-chaincode-devmode.md
> +在启动peer时设置了调试日志，可以确认链码注册是成功的。在peer日志中，你可以看到类似结果:
```suggestion
因为我们在在启动peer时设置了调试日志，可以通过日志来确认链码注册是成功的。在peer日志中，你可以看到类似结果:
```

2023-08-30 10:16 UTC, Chengxuan commented on docs/locale/zh_CN/source/peer-chaincode-devmode.md
> +现在需要运行下列Fabric链码生命周期命令，以同意并将链码提交到通道中:
Approve可能翻译为”认证“或者“认可“更书面语一点。

2023-08-30 10:17 UTC, Chengxuan requested changes
@winterpi 我提交了一些修改的建议，请您看一下

2023-08-31 10:12 UTC, winterpi commented
好的，没问题，多谢再次校对。

要怎么合并？

2023-08-31 10:26 UTC, Chengxuan commented
@winterpi 如果对反馈满意，可以直接加进这个请求，具体操作文档：https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request

对于链码翻译的建议，估计要加一个commit.

2023-08-31 11:31 UTC, zRich commented on docs/locale/zh_CN/source/peer-chaincode-devmode.md
> +**注意:** 为了在peer上使用开发模式("DevMode")，网络中的所有节点必须禁用TLS通信。在生产网络环境下强烈推荐使用TLS通信，所以永远不要在开发模式下启动一台生产型peer。不要将本教程中使用的网络作为任何形式的生产网络的模板。参考[部署一个生产网络](deployment_guide_overview.html)来了解怎样部署一个生产型网络。还可以参考 [Fabric测试网络
统一比较好，用链码

2023-08-31 11:32 UTC, zRich requested changes
把chaincode统一翻译成链码吧

2023-09-04 02:13 UTC, winterpi commented
sorry, 我周末在校对 "couchdb_tutorial.rst#5"，好像默认给合并到这个 PR 上了。

2023-09-14 12:00 UTC, zRich approved these changes

2023-09-14 12:04 UTC, zRich approved these changes

2023-09-14 12:04 UTC, merged

2023-09-16 13:11 UTC, terizhao commented on docs/locale/zh_CN/source/couchdb_tutorial.rst
> +CouchDB 是一个可选的、可替换的状态数据库，支持将账本的数据转为 JSON 格式，并数据内容的富查询，而不仅仅是基于 key 的查询。
建议把rich queries 翻译为多样查询。